#!/usr/bin/env python3

"""
Traverse a chain of symlinks, similarly to namei.
"""

import sys
import os
from pathlib import Path


def main(path):
    while True:
        print(path)
        for ancestor in list(reversed(path.parents)) + [path]:
            if ancestor.is_symlink():
                break
        else:
            return

        target = ancestor.readlink()
        # print(ancestor, "->", target)
        if not target.is_absolute():
            target = ancestor.parent / target

        path = target / path.relative_to(ancestor)


if __name__ == "__main__":
    main(Path(sys.argv[1]))
